### PR TITLE
Update to Routerify v2

### PR DESCRIPTION
**Pull request by seanpianka**
Keeping in line with dep updates, removed broken example since I can't fix stream_body

### CODE REVIEW

**Review by ta3pks — APPROVED** [review]

**Comment by NikosEfthias** [comment]
since this is a version bumb I am gonna merge it not to make things longer @rousan @gsserge for the future if you are not okay with this  for simple prs please let me know so I can wait for your approval as well

**Comment by ta3pks** [comment]
I merged this by mistake can then reverted can you please reopen the pr against the develop branch @seanpianka

**Comment by seanpianka** [comment]
I don't think that's necessary. We can commit to master and make a new release.

**Comment by ta3pks** [comment]
Since I'm not able to create a release @rousan should merge this then

**Comment by seanpianka** [comment]
Can you revert your reverting PR @NikosEfthias

**Comment by ta3pks** [comment]
I dont think I can do that @seanpianka

**Pull request merged**
